"""Post-fix: add `chunk_id` and `contributor` to every src_*.yaml's
`_contribution` block, and add `_contribution` wrapper to unreachable.yaml.

The _refresh_worker.py output omitted these required fields. Validator
flagged them. This patch script edits in-place and is idempotent.
"""
from __future__ import annotations

from pathlib import Path
import yaml

OUT_DIR = Path(__file__).resolve().parent
CHUNK_ID = "source-recency-refresh-50-2026-04-29-0030"
CONTRIBUTOR = "claude-anthropic-internal"


def fix_src_files() -> int:
    fixed = 0
    for path in sorted(OUT_DIR.glob("src_*.yaml")):
        text = path.read_text(encoding="utf-8")
        data = yaml.safe_load(text)
        if not isinstance(data, dict):
            continue
        cb = data.get("_contribution")
        if not isinstance(cb, dict):
            continue
        if "chunk_id" not in cb:
            cb["chunk_id"] = CHUNK_ID
        if "contributor" not in cb:
            cb["contributor"] = CONTRIBUTOR
        if "submission_date" not in cb:
            cb["submission_date"] = "2026-04-29"
        path.write_text(
            yaml.safe_dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False),
            encoding="utf-8",
        )
        fixed += 1
    return fixed


def _report_only_wrapper(notes: str) -> dict:
    return {
        "chunk_id": CHUNK_ID,
        "contributor": CONTRIBUTOR,
        "submission_date": "2026-04-29",
        "ai_tool": "claude-code",
        "ai_model": "claude-opus-4-7",
        # target_action + target_entity_id intentionally absent — this is a
        # report-only file, not an entity sidecar (filename does not start
        # with bma_/bio_/drug_/ind_/source_stub_).
        "notes_for_reviewer": notes,
    }


def fix_report_file(p: Path, notes: str) -> bool:
    if not p.is_file():
        return False
    data = yaml.safe_load(p.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        return False
    if "_contribution" in data and isinstance(data["_contribution"], dict):
        cb = data["_contribution"]
        # Backfill the contribution-meta required fields, leave target-* alone
        for key, val in _report_only_wrapper(notes).items():
            cb.setdefault(key, val)
        # Strip any invalid target_action/target_entity_id from prior buggy run
        cb.pop("target_action", None)
        cb.pop("target_entity_id", None)
    else:
        wrapped = {"_contribution": _report_only_wrapper(notes)}
        for k, v in data.items():
            wrapped[k] = v
        data = wrapped
    p.write_text(
        yaml.safe_dump(data, sort_keys=False, allow_unicode=True, default_flow_style=False),
        encoding="utf-8",
    )
    return True


def fix_unreachable() -> bool:
    return fix_report_file(
        OUT_DIR / "unreachable.yaml",
        notes=(
            "Report-only flag list: sources whose URL HEAD check did not return "
            "2xx/3xx. NOT an upsert (no target_action). The 16 × HTTP 403 are "
            "likely publisher bot-blocking (real browser would succeed); 2 × "
            "HTTP 404 are genuinely broken — maintainer should verify in a "
            "browser before next action."
        ),
    )


def fix_refresh_summary() -> bool:
    return fix_report_file(
        OUT_DIR / "refresh_summary.yaml",
        notes=(
            "Report-only aggregate stats for chunk #33. Generated by "
            "_refresh_worker.py. NOT an upsert (no target_action)."
        ),
    )


def main() -> int:
    fixed = fix_src_files()
    print(f"  Fixed {fixed} src_*.yaml files (added chunk_id + contributor + submission_date)")
    if fix_unreachable():
        print("  Fixed unreachable.yaml (report-only wrapper)")
    if fix_refresh_summary():
        print("  Fixed refresh_summary.yaml (report-only wrapper)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
