"""Gallery cases — CaseEntry dataclass, category list, the CASES table.

Extracted from scripts/build_site.py to keep that file focused on
build orchestration. CASES is pure data (one entry per pre-rendered
sample patient profile shown in the public gallery).

Each entry maps a synthetic patient JSON (under examples/) to a case-id,
a UA label/summary, a Plan-vs-DiagnosticBrief badge, and a category for
the gallery filter chips. Helper functions `_plan()` and `_diag()` exist
only to keep the literal table compact.
"""

from __future__ import annotations

from dataclasses import dataclass



@dataclass
class CaseEntry:
    case_id: str
    file: str
    label_ua: str
    summary_ua: str
    badge: str
    badge_class: str
    # Disease-group classification used by the gallery filter chips.
    # One of: "b_aggressive", "b_indolent", "t_cell", "hodgkin",
    # "myeloma", "myeloid", "lymphoblastic", "solid", "diagnostic".
    # See CASE_CATEGORIES below.
    category: str = "b_aggressive"


CASE_CATEGORIES: list[tuple[str, str, str]] = [
    # (key, ua_label, en_label) — order = display order in filter chips
    ("b_aggressive",   "B-клітинні агресивні",   "B-cell aggressive"),
    ("b_indolent",     "B-клітинні індолентні",  "B-cell indolent"),
    ("t_cell",         "T-клітинні",             "T-cell"),
    ("hodgkin",        "Ходжкіна",               "Hodgkin"),
    ("myeloma",        "Мієлома",                "Myeloma"),
    ("myeloid",        "Мієлоїдні (AML/MDS/MPN)", "Myeloid (AML/MDS/MPN)"),
    ("lymphoblastic",  "Лімфобластні (ALL/LBL)",  "Lymphoblastic (ALL/LBL)"),
    ("solid",          "Солідні пухлини",         "Solid tumors"),
    ("diagnostic",     "Діагностика (pre-biopsy)", "Diagnostic (pre-biopsy)"),
]


CASES: list[CaseEntry] = [
    CaseEntry(
        case_id="hcv-mzl-reference",
        file="patient_zero_reference_case.json",
        label_ua="HCV-MZL · Reference Case (Patient Zero)",
        summary_ua="Чоловік 49, ECOG 1, 5.3 см ураження кореня язика, HCV генотип 1b, indolent presentation. Acceptance test для P0.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="hcv-mzl-bulky",
        file="patient_hcv_mzl_aggressive_burden.json",
        label_ua="HCV-MZL · Aggressive Burden (BR + concurrent DAA)",
        summary_ua="HCV-MZL із bulky disease (>7 см) — RF-BULKY-DISEASE fired. Engine обирає BR (бендамустин+ритуксимаб) + concurrent DAA. Поєднує колишні patient_zero_bulky та новий fixture aggressive_burden.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="hcv-mzl-post-daa",
        file="patient_hcv_mzl_post_daa_responder.json",
        label_ua="HCV-MZL · Post-DAA Responder (Surveillance)",
        summary_ua="Пацієнт post-DAA з SVR12 + lymphoma response — engine обирає surveillance only; план для re-treatment trigger при relapse.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="mm-standard-risk",
        file="patient_mm_standard_risk.json",
        label_ua="Multiple Myeloma · Standard-Risk",
        summary_ua="Newly-diagnosed MM, t(11;14) + hyperdiploid, R-ISS II — engine обирає триплет VRd як default.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="myeloma",
    ),
    CaseEntry(
        case_id="mm-high-risk",
        file="patient_mm_high_risk.json",
        label_ua="Multiple Myeloma · High-Risk",
        summary_ua="Newly-diagnosed MM, t(4;14) + gain 1q21, R2-ISS III — RF-MM-HIGH-RISK-CYTOGENETICS, engine обирає квадруплет D-VRd.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="myeloma",
    ),
    CaseEntry(
        case_id="diagnostic-lymphoma-suspect",
        file="patient_diagnostic_lymphoma_suspect.json",
        label_ua="Suspect Lymphoma · Pre-Biopsy (Diagnostic Brief)",
        summary_ua="Pre-biopsy режим — engine генерує Workup Brief, не Treatment Plan (CHARTER §15.2 C7 — без histology немає лікування).",
        badge="Diagnostic Brief",
        badge_class="bdg-diag",
        category="diagnostic",
    ),
    CaseEntry(
        case_id="diagnostic-lymphoma-confirmed",
        file="patient_diagnostic_lymphoma_confirmed.json",
        label_ua="Lymphoma Confirmed · Post-Biopsy (Treatment Plan)",
        summary_ua="Той самий пацієнт після підтвердження гістології — diagnostic→treatment promotion через revise_plan.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="diagnostic",
    ),
    # ── Tier 1 lymphomas (DLBCL, FL, CLL, MCL — added in marathon block) ──
    CaseEntry(
        case_id="dlbcl-low-ipi",
        file="patient_dlbcl_low_ipi.json",
        label_ua="DLBCL NOS · Low-IPI (R-CHOP standard)",
        summary_ua="Чоловік 54, ECOG 1, IPI 1, GCB cell-of-origin — engine обирає R-CHOP × 6 циклів як default. Найпоширеніша агресивна лімфома (~30% NHL).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_aggressive",
    ),
    CaseEntry(
        case_id="dlbcl-high-ipi",
        file="patient_dlbcl_high_ipi.json",
        label_ua="DLBCL NOS · High-IPI (Pola-R-CHP)",
        summary_ua="Жінка 67, IPI 4, multiple extranodal — RF-DLBCL-HIGH-IPI fired. Engine ескалує до Pola-R-CHP (POLARIX trial); Ukraine-funding caveat.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_aggressive",
    ),
    CaseEntry(
        case_id="fl-low-burden",
        file="patient_fl_low_burden.json",
        label_ua="Follicular · Low Burden (Watch-and-Wait)",
        summary_ua="FL grade 1-2, asymptomatic, no GELF criteria — engine обирає surveillance трек (3 plans usable side-by-side, default = W&W).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="fl-high-burden",
        file="patient_fl_high_burden.json",
        label_ua="Follicular · High Burden (BR)",
        summary_ua="FL з 8 cm масою + B-symptoms + LDH↑ — RF-FL-HIGH-TUMOR-BURDEN-GELF fired. Engine обирає BR (бендамустин + ритуксимаб); reuse REG-BR-STANDARD з HCV-MZL.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="fl-transformation",
        file="patient_fl_transformation.json",
        label_ua="Follicular · Transformation Suspect (R-CHOP)",
        summary_ua="FL з rapid progression + LDH doubling — RF-FL-TRANSFORMATION-SUSPECT fired. Engine обирає R-CHOP (трактує як DLBCL pathway).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="cll-low-risk",
        file="patient_cll_low_risk.json",
        label_ua="CLL/SLL · Low-Risk (BTKi continuous)",
        summary_ua="ХЛЛ зі стандартним ризиком (no TP53/del 17p/IGHV-unmut) — engine обирає acalabrutinib continuous; modern era замість FCR/BR.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="cll-high-risk",
        file="patient_cll_high_risk.json",
        label_ua="CLL/SLL · High-Risk (VenO time-limited)",
        summary_ua="ХЛЛ з TP53 mutation + IGHV-unmut + complex karyotype — RF-CLL-HIGH-RISK fired. Engine ескалує до venetoclax+obinutuzumab (CLL14).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="mcl-fit-younger",
        file="patient_mcl_fit_younger.json",
        label_ua="Mantle Cell · Fit Younger (Intensive + autoSCT)",
        summary_ua="MCL вік 58, ECOG 0, TP53-wt — engine обирає intensive R-CHOP/R-DHAP × 6 + autoSCT + R-maintenance × 3 years (Nordic protocol).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_aggressive",
    ),
    CaseEntry(
        case_id="mcl-unfit-tp53",
        file="patient_mcl_unfit_or_tp53.json",
        label_ua="Mantle Cell · Unfit / TP53-mutant (BTKi+R)",
        summary_ua="MCL вік 71, ECOG 2, TP53 mutation — RF-MCL-BLASTOID-OR-TP53 fired. Engine обирає acalabrutinib + rituximab (BTKi-based).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_aggressive",
    ),
    # ── More Tier 1 (MZL splenic + nodal, Burkitt, HCL, WM, HGBL-DH) ────
    CaseEntry(
        case_id="smzl-hcv-positive",
        file="patient_smzl_hcv_positive.json",
        label_ua="Splenic MZL · HCV-positive (DAA antiviral)",
        summary_ua="Селезінкова MZL із HCV-позитивним статусом — engine обирає DAA antiviral (sofosbuvir/velpatasvir 12 тижнів) як 1L; reuse REG-DAA-SOF-VEL з HCV-MZL extranodal.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="smzl-hcv-negative",
        file="patient_smzl_hcv_negative.json",
        label_ua="Splenic MZL · HCV-negative (Rituximab mono)",
        summary_ua="Селезінкова MZL HCV-negative — engine обирає rituximab monotherapy (4 weekly + 2-year maintenance).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="nmzl-low-burden",
        file="patient_nmzl_low_burden.json",
        label_ua="Nodal MZL · Low Burden (W&W)",
        summary_ua="Нодальна MZL без GELF-критеріїв — engine обирає surveillance трек (повторює FL-парадигму).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="burkitt-low-risk",
        file="patient_burkitt_low_risk.json",
        label_ua="Burkitt · Low/Intermediate Risk (DA-EPOCH-R)",
        summary_ua="Burkitt без CNS+, LDH в нормі — engine обирає DA-EPOCH-R (CALGB 10002, ~90% CR including HIV+).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_aggressive",
    ),
    CaseEntry(
        case_id="burkitt-high-risk",
        file="patient_burkitt_high_risk.json",
        label_ua="Burkitt · High Risk (CODOX-M / IVAC)",
        summary_ua="Burkitt з CNS involvement + LDH >3× ULN + bulky abdomen — RF-BURKITT-HIGH-RISK fired. Engine обирає Magrath protocol з HD-MTX + IT MTX/cytarabine.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_aggressive",
    ),
    CaseEntry(
        case_id="hcl-typical",
        file="patient_hcl_typical.json",
        label_ua="Hairy Cell Leukemia (Cladribine 7-day)",
        summary_ua="Волосатоклітинний лейкоз з cytopenia + splenomegaly — engine обирає 1 курс cladribine 7 днів. ~85% durable CR.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="wm-myd88-positive",
        file="patient_wm_myd88_positive.json",
        label_ua="Waldenström · MYD88-positive (Zanubrutinib)",
        summary_ua="WM з MYD88 L265P + iwWM treatment indication — engine обирає zanubrutinib (ASPEN — superior до ibrutinib).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_indolent",
    ),
    CaseEntry(
        case_id="hgbl-double-hit",
        file="patient_hgbl_double_hit.json",
        label_ua="HGBL · Double-Hit (DA-EPOCH-R)",
        summary_ua="High-Grade B-Cell Lymphoma з MYC + BCL2 break-apart — engine обирає DA-EPOCH-R (substantial OS improvement vs R-CHOP); reuse схеми з Burkitt.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="b_aggressive",
    ),
    # ── T-cell block + Hodgkin (final marathon block) ──────────────────────
    CaseEntry(
        case_id="alcl-alk-negative",
        file="patient_alcl_alk_negative.json",
        label_ua="ALCL · ALK-negative (CHP-Bv)",
        summary_ua="Системна анапластична великоклітинна лімфома, ALK-negative — universally CD30+. Engine обирає CHP-Bv (ECHELON-2: brentuximab замість vincristine).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="t_cell",
    ),
    CaseEntry(
        case_id="ptcl-cd30-negative",
        file="patient_ptcl_cd30_negative.json",
        label_ua="PTCL NOS · CD30-negative (CHOEP)",
        summary_ua="Периферична T-клітинна лімфома, CD30-negative — engine обирає CHOEP (CHOP + etoposide). CD30+ варіант ескалював би до CHP-Bv.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="t_cell",
    ),
    CaseEntry(
        case_id="aitl-cd30-positive",
        file="patient_aitl_cd30_positive.json",
        label_ua="AITL · CD30-positive (CHP-Bv)",
        summary_ua="Ангіоімунобластна T-клітинна лімфома, CD30+ — RF-TCELL-CD30-POSITIVE fired. Engine обирає CHP-Bv.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="t_cell",
    ),
    CaseEntry(
        case_id="chl-advanced",
        file="patient_chl_advanced.json",
        label_ua="Classical Hodgkin · Advanced (A+AVD)",
        summary_ua="Стадія IV cHL — RF-CHL-ADVANCED-STAGE fired. Engine обирає A+AVD (ECHELON-1: brentuximab замість bleomycin, superior OS).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="hodgkin",
    ),
    CaseEntry(
        case_id="chl-early",
        file="patient_chl_early.json",
        label_ua="Classical Hodgkin · Early Stage (ABVD)",
        summary_ua="Стадія IIA cHL, без advanced criteria — engine обирає ABVD × 2-4 + ISRT (response-adapted).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="hodgkin",
    ),
    CaseEntry(
        case_id="nlpbl-early",
        file="patient_nlpbl_early.json",
        label_ua="NLPBL · Early Stage (Observation / RT)",
        summary_ua="Нодулярна лімфоцит-домінантна B-клітинна лімфома (перекласифіковано WHO 5th-ed з NLPHL у B-cell) — early stage. Engine обирає observation / ISRT alone.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="hodgkin",
    ),
    # ── Tier 3 deepening: AITL CD30-neg + MF/Sézary block + NLPBL alt arm ──
    CaseEntry(
        case_id="aitl-cd30-negative",
        file="patient_aitl_cd30_negative.json",
        label_ua="AITL · CD30-negative (CHOEP + AITL-specific workup)",
        summary_ua="AITL з CD30-negative біопсією — engine обирає AITL-specific CHOEP. Layered workup: EBER-ISH (EBV+ B-cell мікрооточення), IgG quant (paraneoplastic hypogamma), DAT (AIHA risk).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="t_cell",
    ),
    CaseEntry(
        case_id="mf-early-stage",
        file="patient_mf_early_stage.json",
        label_ua="Mycosis Fungoides · Early Stage (Skin-Directed)",
        summary_ua="MF stage IB без B2/LCT — engine обирає skin-directed (NBUVB / topicals / TSEBT). Жодного системного режиму — preserves chemo для прогресу. Workup rules out occult Sézary (B2 count) + LCT.",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="t_cell",
    ),
    CaseEntry(
        case_id="sezary-advanced",
        file="patient_sezary_advanced.json",
        label_ua="Sézary Syndrome · Advanced (Mogamulizumab)",
        summary_ua="Sézary syndrome (B2 leukemic, generalized erythroderma) — RF-MF-SEZARY-LEUKEMIC fired. Engine обирає mogamulizumab (MAVORIC: anti-CCR4 ADCC, найкраща blood-compartment відповідь).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="t_cell",
    ),
    CaseEntry(
        case_id="mf-advanced-cd30",
        file="patient_mf_advanced_cd30.json",
        label_ua="MF · Advanced + CD30+ LCT (Brentuximab mono)",
        summary_ua="Advanced MF stage IIB з large-cell transformation, CD30+ — RF-MF-LARGE-CELL-TRANSFORMATION + RF-TCELL-CD30-POSITIVE fired. Engine обирає brentuximab vedotin monotherapy (ALCANZA).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="t_cell",
    ),
    CaseEntry(
        case_id="nlpbl-ia-rituximab",
        file="patient_nlpbl_ia_rituximab.json",
        label_ua="NLPBL · IA + RT-contraindicated (Rituximab mono)",
        summary_ua="NLPBL stage IA у молодої жінки з cervical adenopathy — RT-contraindicated через breast/thyroid field overlap. Engine обирає rituximab monotherapy alternative (CD20+ B-cell biology, НЕ ABVD).",
        badge="Treatment Plan",
        badge_class="bdg-plan",
        category="hodgkin",
    ),
    # ── B-cell aggressive: extra DLBCL/HGBL/PMBCL/PCNSL (relapsed + new diseases) ──
    CaseEntry(
        case_id="dlbcl-chemorefractory-cart",
        file="patient_dlbcl_chemorefractory_for_cart.json",
        label_ua="DLBCL NOS · Primary Chemorefractory (CAR-T axi-cel)",
        summary_ua="DLBCL з primary refractory disease (PD на R-CHOP) — engine обирає axi-cel CAR-T (ZUMA-7: 2L CAR-T > salvage+autoSCT для early-failure).",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    CaseEntry(
        case_id="dlbcl-relapsed-te-ineligible",
        file="patient_dlbcl_relapsed_transplant_ineligible.json",
        label_ua="DLBCL NOS · Relapsed (Transplant-Ineligible)",
        summary_ua="DLBCL relapsed, transplant-ineligible через age + comorbidity — engine обирає Pola-BR (POLARGO) або loncastuximab tesirine.",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    CaseEntry(
        case_id="hgbl-primary-refractory",
        file="patient_hgbl_primary_refractory.json",
        label_ua="HGBL · Primary Refractory (Early CAR-T)",
        summary_ua="HGBL-DH що не відповів на DA-EPOCH-R — engine обирає axi-cel CAR-T (ZUMA-7); chemosensitivity-test позитивний для late-relapse → salvage+autoSCT.",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    CaseEntry(
        case_id="pmbcl-typical",
        file="patient_pmbcl_typical.json",
        label_ua="PMBCL · Typical (DA-EPOCH-R)",
        summary_ua="Молода жінка з anterior mediastinal mass — engine обирає DA-EPOCH-R без RT (NCI 2013: ~93% EFS, обхід RT-токсичності для AYA).",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    CaseEntry(
        case_id="pmbcl-bulky-svc",
        file="patient_pmbcl_bulky_svc.json",
        label_ua="PMBCL · Bulky + SVC Syndrome",
        summary_ua="PMBCL з bulky mediastinal mass + SVC compression — engine додає upfront pre-phase steroids + airway management до DA-EPOCH-R.",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    CaseEntry(
        case_id="pmbcl-relapsed-post-rchop",
        file="patient_pmbcl_relapsed_post_rchop.json",
        label_ua="PMBCL · Relapsed post-R-CHOP (Pembrolizumab)",
        summary_ua="PMBCL relapsed/refractory після R-CHOP — engine обирає R-ICE+autoSCT (eligible) або pembrolizumab (KEYNOTE-170, ineligible/refractory).",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    CaseEntry(
        case_id="pcnsl-typical",
        file="patient_pcnsl_typical.json",
        label_ua="PCNSL · Typical (R-MPV → autoSCT)",
        summary_ua="Імунокомпетентний пацієнт з biopsy-confirmed PCNSL — engine обирає R-MPV induction → thiotepa-based autoSCT consolidation (MATRix/IELSG 32).",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    CaseEntry(
        case_id="pcnsl-elderly-frail",
        file="patient_pcnsl_elderly_frail.json",
        label_ua="PCNSL · Elderly Frail (R-MTX-attenuated)",
        summary_ua="PCNSL вік 75, ECOG 2 — engine обирає attenuated MTX-based induction без autoSCT consolidation; lenalidomide maintenance як альтернатива.",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    CaseEntry(
        case_id="pcnsl-immunocompromised-ebv",
        file="patient_pcnsl_immunocompromised_ebv.json",
        label_ua="PCNSL · Immunocompromised + EBV+ (Restore Immunity)",
        summary_ua="PCNSL у HIV+/post-transplant пацієнта, EBER+ — engine додає immune-restoration (HAART / RIS) перед HD-MTX; rituximab якщо CD20+.",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_aggressive",
    ),
    # ── B-cell indolent: relapsed + new diseases ──
    CaseEntry(
        case_id="cll-post-btki",
        file="patient_cll_post_btki_progression.json",
        label_ua="CLL/SLL · Post-BTKi Progression (Pirtobrutinib / VenR)",
        summary_ua="CLL з прогресією на covalent BTKi — engine обирає pirtobrutinib (BRUIN, non-covalent) або venetoclax+rituximab (MURANO).",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_indolent",
    ),
    CaseEntry(
        case_id="hcl-relapsed-braf",
        file="patient_hcl_relapsed_braf.json",
        label_ua="HCL · Relapsed BRAF-V600E+ (Vemurafenib + Rituximab)",
        summary_ua="HCL relapsed з BRAF-V600E+ — engine обирає vemurafenib+rituximab (Tiacci); BRAF-WT route → cladribine retreatment.",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_indolent",
    ),
    CaseEntry(
        case_id="wm-cxcr4-mut",
        file="patient_wm_cxcr4_mut.json",
        label_ua="Waldenström · CXCR4-mutant (BR fixed-duration)",
        summary_ua="WM з MYD88+ AND CXCR4-mutant — RF-WM-CXCR4-MUT fired (CXCR4 знижує BTKi response). Engine обирає BR fixed-duration або zanubrutinib з extended observation.",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_indolent",
    ),
    CaseEntry(
        case_id="nmzl-high-burden",
        file="patient_nmzl_high_burden.json",
        label_ua="Nodal MZL · High Burden (BR)",
        summary_ua="Нодальна MZL з GELF+ — engine обирає BR (1L); 2L після rituximab/W&W failure теж BR.",
        badge="Treatment Plan", badge_class="bdg-plan", category="b_indolent",
    ),
    # ── T-cell: ALCL ALK+ + relapsed + PTCL CD30+ + EATL/HSTCL/T-PLL/ATLL/NK-T/PTLD ──
    CaseEntry(
        case_id="alcl-alk-positive-typical",
        file="patient_alcl_alk_positive_typical.json",
        label_ua="ALCL · ALK-positive Typical (CHP-Bv)",
        summary_ua="Молода особа з ALK+ ALCL — engine обирає CHP-Bv (ECHELON-2). ALK+ має значно кращий прогноз vs ALK-.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="alcl-relapsed-bv-naive",
        file="patient_alcl_relapsed_bv_naive.json",
        label_ua="ALCL · Relapsed BV-naive (Brentuximab → autoSCT)",
        summary_ua="Relapsed ALCL без попереднього brentuximab — engine обирає brentuximab mono → autoSCT consolidation; BV maintenance per ECHELON-2 update.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="ptcl-cd30-positive",
        file="patient_ptcl_cd30_positive.json",
        label_ua="PTCL NOS · CD30-positive (CHP-Bv)",
        summary_ua="PTCL NOS, CD30≥10% — RF-TCELL-CD30-POSITIVE fired. Engine обирає CHP-Bv (ECHELON-2 inclusion threshold).",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="ptcl-relapsed",
        file="patient_ptcl_relapsed.json",
        label_ua="PTCL NOS · Relapsed post-autoSCT (Romidepsin / Pralatrexate)",
        summary_ua="PTCL NOS relapsed після autoSCT — engine обирає romidepsin або pralatrexate; alloHCT як curative-intent для chemosensitive.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="aitl-relapsed-2l",
        file="patient_aitl_relapsed_2l.json",
        label_ua="AITL · Relapsed 2L (Azacitidine)",
        summary_ua="AITL relapsed з TET2/DNMT3A epigenetic profile — engine обирає azacitidine (epigenetic targeting; AITL — найбільш azacitidine-responsive TCL subtype).",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="eatl-typical",
        file="patient_eatl_typical.json",
        label_ua="EATL · Typical (Celiac, CHOEP → autoSCT)",
        summary_ua="EATL у пацієнта з celiac disease — engine обирає CHOEP induction → autoSCT consolidation (NLG-T-01).",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="eatl-relapsed-post-choep",
        file="patient_eatl_relapsed_post_choep.json",
        label_ua="EATL · Relapsed post-CHOEP (ICE Salvage)",
        summary_ua="EATL relapsed після CHOEP — engine обирає ICE salvage; alloHCT для chemosensitive.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="hstcl-fit-younger",
        file="patient_hstcl_fit_younger.json",
        label_ua="HSTCL · Fit Younger (ICE/IVAC → alloHCT)",
        summary_ua="Hepatosplenic T-cell Lymphoma у молодої особи, ECOG 0 — engine обирає intensive ICE/IVAC → upfront alloHCT (CHOP неадекватний).",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="hstcl-iatrogenic-ibd",
        file="patient_hstcl_iatrogenic_ibd.json",
        label_ua="HSTCL · Iatrogenic IBD (CHOEP-unfit fallback)",
        summary_ua="HSTCL у IBD-пацієнта на тривалій thiopurine+anti-TNF therapy — engine припиняє imunosuppression + CHOEP-unfit fallback з branching algorithm.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="t-pll-typical",
        file="patient_t_pll_typical.json",
        label_ua="T-PLL · Typical (Alemtuzumab IV)",
        summary_ua="T-PLL з ATM mutation + TCL1A rearrangement — engine обирає alemtuzumab IV (~90% ORR) → alloHCT consolidation.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="t-pll-alem-refractory",
        file="patient_t_pll_alemtuzumab_refractory.json",
        label_ua="T-PLL · Alemtuzumab-refractory (Venetoclax + Alem)",
        summary_ua="T-PLL refractory до alemtuzumab mono — engine обирає venetoclax + alemtuzumab combo (Boidol/Hampel).",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="atll-acute",
        file="patient_atll_acute.json",
        label_ua="ATLL · Acute (mLSG15 / EPOCH)",
        summary_ua="Adult T-cell Leukemia/Lymphoma, acute subtype, HTLV-1+ — engine обирає intensive mLSG15 або EPOCH; alloHCT consolidation для responders.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="atll-indolent-smoldering",
        file="patient_atll_indolent_smoldering.json",
        label_ua="ATLL · Indolent / Smoldering (Watchful Waiting)",
        summary_ua="ATLL indolent/smoldering — engine обирає observation; system trigger для transformation.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="nk-t-nasal-localized",
        file="patient_nk_t_nasal_localized.json",
        label_ua="NK/T-Nasal · Localized (P-GEMOX + RT)",
        summary_ua="Localized extranodal NK/T-cell lymphoma, nasal type — engine обирає concurrent P-GEMOX + RT (anthracycline-resistant biology).",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="nk-t-nasal-relapsed",
        file="patient_nk_t_nasal_relapsed.json",
        label_ua="NK/T-Nasal · Relapsed (Avelumab)",
        summary_ua="NK/T-nasal relapsed — engine обирає avelumab (NCCN-listed PD-L1 inhibitor; promoted from stub).",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="mf-relapsed-post-moga",
        file="patient_mf_relapsed_post_moga.json",
        label_ua="MF · Relapsed post-Mogamulizumab (Bexarotene)",
        summary_ua="MF/Sézary relapsed після mogamulizumab — engine обирає bexarotene 2L з low-dose maintenance (RXR-targeted oral retinoid).",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="ptld-polymorphic-ebv",
        file="patient_ptld_polymorphic_ebv.json",
        label_ua="PTLD · Polymorphic EBV+ (RIS + Rituximab)",
        summary_ua="Post-transplant LPD, polymorphic EBV+ — engine обирає RIS (reduce immunosuppression) + sequential PTLD-1 rituximab maintenance.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    CaseEntry(
        case_id="ptld-monomorphic-dlbcl-like",
        file="patient_ptld_monomorphic_dlbcl_like.json",
        label_ua="PTLD · Monomorphic DLBCL-like (R-CHOP)",
        summary_ua="Monomorphic PTLD з DLBCL morphology — engine обирає R-CHOP після RIS-failure; sequential treatment per PTLD-1.",
        badge="Treatment Plan", badge_class="bdg-plan", category="t_cell",
    ),
    # ── Hodgkin: pediatric + relapsed ──
    CaseEntry(
        case_id="chl-pediatric-bulky",
        file="patient_chl_pediatric_bulky_mediastinal.json",
        label_ua="cHL · AYA Stage IIB Bulky Mediastinal",
        summary_ua="AYA пацієнт з cHL stage IIB + bulky mediastinal mass + B-symptoms — RF-CHL-BULKY-MEDIASTINAL fired. Response-adapted intensification.",
        badge="Treatment Plan", badge_class="bdg-plan", category="hodgkin",
    ),
    CaseEntry(
        case_id="chl-relapsed-salvage",
        file="patient_chl_relapsed_for_salvage.json",
        label_ua="cHL · Relapsed (Salvage → autoSCT + BV maint.)",
        summary_ua="cHL relapsed після ABVD/A+AVD — engine обирає salvage chemo (ICE/DHAP) → autoSCT → brentuximab maintenance (AETHERA).",
        badge="Treatment Plan", badge_class="bdg-plan", category="hodgkin",
    ),
    # ── Myeloma: relapsed (post-VRd + triple-class refractory) ──
    CaseEntry(
        case_id="mm-post-vrd-progression",
        file="patient_mm_post_vrd_progression.json",
        label_ua="Multiple Myeloma · Post-VRd Progression (DPd / IsaPd)",
        summary_ua="MM relapsed після VRd induction — engine обирає daratumumab+pomalidomide+dex (APOLLO) або isatuximab+Pd (ICARIA).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloma",
    ),
    CaseEntry(
        case_id="mm-triple-class-refractory",
        file="patient_mm_triple_class_refractory.json",
        label_ua="Multiple Myeloma · Triple-Class Refractory (CAR-T / Teclistamab)",
        summary_ua="MM triple-class refractory (PI + IMiD + anti-CD38) — engine обирає cilta-cel/ide-cel CAR-T або teclistamab BCMA-T-cell engager.",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloma",
    ),
    # ── Myeloid: AML / APL / CML / MDS-HR / MDS-LR / PV / ET / PMF ──
    CaseEntry(
        case_id="aml-fit-1l-7-3",
        file="patient_aml_fit_1l_seven_three.json",
        label_ua="AML · Fit 1L (7+3 Induction)",
        summary_ua="Newly-diagnosed AML, fit, ELN intermediate — engine обирає 7+3 induction (cytarabine + daunorubicin) → consolidation HiDAC.",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="aml-unfit-ven-aza",
        file="patient_aml_unfit_ven_aza.json",
        label_ua="AML · Unfit (Venetoclax + Azacitidine)",
        summary_ua="AML вік 78, ECOG 2 — engine обирає ven+aza (VIALE-A: ~65% CR/CRi, OS 14.7 mo, краще ніж aza alone).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="aml-flt3-relapse",
        file="patient_aml_flt3_relapse.json",
        label_ua="AML · FLT3-mutant Relapse (Gilteritinib)",
        summary_ua="AML relapsed з FLT3-ITD/TKD — engine обирає gilteritinib mono (ADMIRAL: superior до salvage chemo); alloHCT для responders.",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="apl-low-risk",
        file="patient_apl_low_risk.json",
        label_ua="APL · Low Risk (ATRA + ATO chemo-free)",
        summary_ua="APL з WBC <10K (low-risk Sanz) — engine обирає ATRA+ATO chemo-free (APL0406: ~98% CR, без anthracycline).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="apl-high-risk",
        file="patient_apl_high_risk.json",
        label_ua="APL · High Risk + DIC (ATRA + ATO + Idarubicin)",
        summary_ua="APL з WBC >10K + active DIC — RF-APL-DIC + RF-APL-HIGH-RISK fired. Engine додає idarubicin до ATRA+ATO; emergency cryoprecipitate/platelets.",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="cml-chronic-newdx",
        file="patient_cml_chronic_phase_newdx.json",
        label_ua="CML · Chronic Phase Newly Diagnosed (TKI 1L)",
        summary_ua="Newly-diagnosed CML chronic phase, BCR-ABL1+ — engine обирає imatinib (low-risk Sokal) або 2G TKI (intermediate/high).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="cml-t315i",
        file="patient_cml_t315i.json",
        label_ua="CML · T315I-mutated (Ponatinib / Asciminib)",
        summary_ua="CML з T315I gatekeeper mutation post-2G TKI — engine обирає ponatinib (PACE) або asciminib (allosteric STAMP-inhibitor).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="cml-blast-crisis",
        file="patient_cml_blast_crisis_at_presentation.json",
        label_ua="CML · Blast Crisis at Presentation (TKI + Chemo + alloHCT)",
        summary_ua="CML що дебютує як blast crisis — engine обирає TKI + intensive chemo bridge → urgent alloHCT (без alloHCT медіана OS <12 mo).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="mds-hr-transplant-eligible",
        file="patient_mds_hr_transplant_eligible.json",
        label_ua="MDS-HR · Transplant-Eligible (Aza Bridge → alloHCT)",
        summary_ua="MDS IPSS-R high, fit, donor available — engine обирає azacitidine bridge → upfront alloHCT (curative).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="mds-hr-unfit-aza",
        file="patient_mds_hr_unfit_aza.json",
        label_ua="MDS-HR · Unfit (Azacitidine Maintenance)",
        summary_ua="MDS-HR transplant-ineligible — engine обирає azacitidine indefinite (AZA-001: median OS 24 mo vs 15 mo для conventional care).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="mds-hr-progression-aml",
        file="patient_mds_hr_progression_to_aml.json",
        label_ua="MDS-HR · Progression to Secondary AML",
        summary_ua="MDS на azacitidine з progression до sAML — engine реагує AML-reroute: ven+aza або 7+3 induction (за fitness).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="mds-lr-del5q",
        file="patient_mds_lr_del5q.json",
        label_ua="MDS-LR · del(5q) (Lenalidomide)",
        summary_ua="MDS-LR з isolated del(5q) syndrome — engine обирає lenalidomide (MDS-004: ~67% transfusion-independence).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="mds-lr-rs-luspatercept",
        file="patient_mds_lr_rs_luspatercept.json",
        label_ua="MDS-LR · RS+ EPO-failure (Luspatercept)",
        summary_ua="MDS-LR з ring sideroblasts + EPO-high (>500) → ESA-failure — engine обирає luspatercept (COMMANDS).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="mds-lr-hypoplastic-ist",
        file="patient_mds_lr_hypoplastic_ist.json",
        label_ua="MDS-LR · Hypoplastic / IST candidate",
        summary_ua="Hypoplastic MDS, mimics aplastic anemia — engine обирає immunosuppressive therapy (ATG+CsA) як alternative до transfusion-only.",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="pv-high-risk-hu",
        file="patient_pv_high_risk_hu.json",
        label_ua="Polycythemia Vera · High Risk (HU 1L)",
        summary_ua="PV вік >60 + thrombosis history — engine обирає phlebotomy + low-dose ASA + cytoreduction hydroxyurea.",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="pv-hu-resistant-rux",
        file="patient_pv_hu_resistant_ruxolitinib.json",
        label_ua="PV · HU-resistant (Ruxolitinib 2L)",
        summary_ua="PV з HU-intolerance/resistance per ELN — engine обирає ruxolitinib (RESPONSE-2: hematocrit control + symptom relief).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="pv-pregnancy-planning",
        file="patient_pv_pregnancy_planning.json",
        label_ua="PV · Pregnancy Planning (Peg-IFN)",
        summary_ua="Reproductive-age жінка з PV, planning pregnancy — engine обирає peg-IFN α-2a (non-teratogenic, fetus-safe).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="et-high-risk-hu",
        file="patient_et_high_risk_hu.json",
        label_ua="Essential Thrombocythemia · High Risk (HU)",
        summary_ua="ET high-risk (age >60 + JAK2+ + thrombosis) — engine обирає hydroxyurea + ASA; anagrelide як 2L (PT-1).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="pmf-anemia-dominant",
        file="patient_pmf_anemia_dominant.json",
        label_ua="PMF · Anemia-Dominant (Momelotinib)",
        summary_ua="PMF DIPSS-Plus int-1, anemia-dominant — engine обирає momelotinib (MOMENTUM: anemia-friendly JAKi).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="pmf-int2-symptomatic-rux",
        file="patient_pmf_int2_symptomatic_ruxolitinib.json",
        label_ua="PMF · Int-2 Symptomatic (Ruxolitinib)",
        summary_ua="PMF DIPSS-Plus int-2 з splenomegaly + constitutional symptoms — engine обирає ruxolitinib (COMFORT-I/II).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    CaseEntry(
        case_id="pmf-post-rux-allohct",
        file="patient_pmf_post_rux_allohct_bridge.json",
        label_ua="PMF · Post-Rux alloHCT Bridge (Urgent)",
        summary_ua="PMF post-ruxolitinib failure з massive splenomegaly + transfusion-dependence — engine обирає alloHCT bridge (curative-intent, urgent).",
        badge="Treatment Plan", badge_class="bdg-plan", category="myeloid",
    ),
    # ── Lymphoblastic: B-ALL / T-ALL / T-LBL ──
    CaseEntry(
        case_id="b-all-ph-pos-adult",
        file="patient_b_all_ph_pos_adult.json",
        label_ua="B-ALL · Ph+ Adult (TKI + Chemo)",
        summary_ua="Adult B-ALL Ph+ (BCR-ABL1+) — engine обирає dasatinib + chemo (hyper-CVAD або pediatric-inspired); alloHCT для CR1 high-risk.",
        badge="Treatment Plan", badge_class="bdg-plan", category="lymphoblastic",
    ),
    CaseEntry(
        case_id="b-all-mrd-positive",
        file="patient_b_all_mrd_positive.json",
        label_ua="B-ALL · MRD-positive (Blinatumomab)",
        summary_ua="B-ALL MRD-positive після induction — engine обирає blinatumomab (BLAST: MRD eradication у >75%).",
        badge="Treatment Plan", badge_class="bdg-plan", category="lymphoblastic",
    ),
    CaseEntry(
        case_id="b-all-t315i-post-tki",
        file="patient_b_all_t315i_post_tki.json",
        label_ua="B-ALL · T315I-mutated post-TKI (Ponatinib + alloHCT)",
        summary_ua="Ph+ B-ALL relapsed з T315I gatekeeper — engine обирає ponatinib + chemo bridge → alloHCT.",
        badge="Treatment Plan", badge_class="bdg-plan", category="lymphoblastic",
    ),
    CaseEntry(
        case_id="t-all-relapsed",
        file="patient_t_all_relapsed_post_hyper_cvad.json",
        label_ua="T-ALL · Relapsed post-hyper-CVAD (Nelarabine)",
        summary_ua="T-ALL relapsed після hyper-CVAD — engine обирає nelarabine (T-cell selective; alloHCT consolidation).",
        badge="Treatment Plan", badge_class="bdg-plan", category="lymphoblastic",
    ),
    CaseEntry(
        case_id="t-lbl-mediastinal",
        file="patient_t_lbl_mediastinal.json",
        label_ua="T-LBL · Mediastinal Mass (Pediatric-inspired ALL)",
        summary_ua="T-lymphoblastic lymphoma з mediastinal mass — engine обирає pediatric-inspired ALL regimen (CALGB 10403 / GMALL); CNS prophylaxis обов'язкове.",
        badge="Treatment Plan", badge_class="bdg-plan", category="lymphoblastic",
    ),
    # ── Solid tumors: Cervical / GBM / Ovarian ──
    CaseEntry(
        case_id="cervical-locally-advanced",
        file="patient_cervical_locally_advanced.json",
        label_ua="Cervical · Locally Advanced (CCRT + Pembrolizumab)",
        summary_ua="Locally advanced cervical cancer (FIGO IIB-IVA) — engine обирає cisplatin-based CCRT + brachytherapy; pembrolizumab maintenance (KEYNOTE-A18).",
        badge="Treatment Plan", badge_class="bdg-plan", category="solid",
    ),
    CaseEntry(
        case_id="gbm-stupp",
        file="patient_gbm_newly_diagnosed_stupp.json",
        label_ua="Glioblastoma · Newly Diagnosed (Stupp Protocol)",
        summary_ua="GBM IDH-WT WHO grade 4 — engine обирає Stupp: maximal safe resection → RT + concurrent TMZ → adjuvant TMZ × 6; TTFields для MGMT-methylated.",
        badge="Treatment Plan", badge_class="bdg-plan", category="solid",
    ),
    CaseEntry(
        case_id="ovarian-advanced-hrd",
        file="patient_ovarian_advanced_hrd.json",
        label_ua="Ovarian · Advanced HRD+ (PARPi maintenance)",
        summary_ua="Advanced high-grade serous ovarian, HRD+ — engine обирає platinum-doublet → PARPi maintenance (olaparib/niraparib; SOLO-1, PRIMA).",
        badge="Treatment Plan", badge_class="bdg-plan", category="solid",
    ),
    # ── AUTO-GENERATED disease-coverage stubs (do not hand-edit; regen via scripts/generate_auto_examples.py) ──
    CaseEntry(
        case_id="auto-aitl",
        file="auto_aitl.json",
        label_ua="DIS-AITL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Angioimmunoblastic T-Cell Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-alcl",
        file="auto_alcl.json",
        label_ua="DIS-ALCL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Anaplastic Large Cell Lymphoma, Systemic. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-aml",
        file="auto_aml.json",
        label_ua="DIS-AML — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Acute Myeloid Leukemia. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-apl",
        file="auto_apl.json",
        label_ua="DIS-APL — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Acute Promyelocytic Leukemia. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-atll",
        file="auto_atll.json",
        label_ua="DIS-ATLL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Adult T-Cell Leukemia/Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-b_all",
        file="auto_b_all.json",
        label_ua="DIS-B-ALL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для B-Lymphoblastic Leukemia/Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="lymphoblastic",
    ),
    CaseEntry(
        case_id="auto-breast",
        file="auto_breast.json",
        label_ua="DIS-BREAST — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Invasive breast cancer. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-burkitt",
        file="auto_burkitt.json",
        label_ua="DIS-BURKITT — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Burkitt Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_aggressive",
    ),
    CaseEntry(
        case_id="auto-cervical",
        file="auto_cervical.json",
        label_ua="DIS-CERVICAL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Cervical carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-chl",
        file="auto_chl.json",
        label_ua="DIS-CHL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Classical Hodgkin Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="hodgkin",
    ),
    CaseEntry(
        case_id="auto-cll",
        file="auto_cll.json",
        label_ua="DIS-CLL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Chronic Lymphocytic Leukemia / Small Lymphocytic Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_indolent",
    ),
    CaseEntry(
        case_id="auto-cml",
        file="auto_cml.json",
        label_ua="DIS-CML — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Chronic Myeloid Leukemia. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-crc",
        file="auto_crc.json",
        label_ua="DIS-CRC — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Colorectal carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-dlbcl_nos",
        file="auto_dlbcl_nos.json",
        label_ua="DIS-DLBCL-NOS — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Diffuse Large B-Cell Lymphoma, Not Otherwise Specified. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_aggressive",
    ),
    CaseEntry(
        case_id="auto-eatl",
        file="auto_eatl.json",
        label_ua="DIS-EATL — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Enteropathy-Associated T-Cell Lymphoma. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-endometrial",
        file="auto_endometrial.json",
        label_ua="DIS-ENDOMETRIAL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Endometrial carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-esophageal",
        file="auto_esophageal.json",
        label_ua="DIS-ESOPHAGEAL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Esophageal carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-et",
        file="auto_et.json",
        label_ua="DIS-ET — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Essential Thrombocythemia. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-fl",
        file="auto_fl.json",
        label_ua="DIS-FL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Follicular Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_indolent",
    ),
    CaseEntry(
        case_id="auto-gastric",
        file="auto_gastric.json",
        label_ua="DIS-GASTRIC — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Gastric and gastroesophageal junction adenocarcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-gbm",
        file="auto_gbm.json",
        label_ua="DIS-GBM — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Glioblastoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-gist",
        file="auto_gist.json",
        label_ua="DIS-GIST — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Gastrointestinal stromal tumor. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-glioma_low_grade",
        file="auto_glioma_low_grade.json",
        label_ua="DIS-GLIOMA-LOW-GRADE — Auto-stub (50% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Low-grade glioma. Фактична наповненість бази для цієї хвороби — 50%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-hcc",
        file="auto_hcc.json",
        label_ua="DIS-HCC — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Hepatocellular carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-hcl",
        file="auto_hcl.json",
        label_ua="DIS-HCL — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Hairy Cell Leukemia. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_indolent",
    ),
    CaseEntry(
        case_id="auto-hcv_mzl",
        file="auto_hcv_mzl.json",
        label_ua="DIS-HCV-MZL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для HCV-associated Marginal Zone Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_indolent",
    ),
    CaseEntry(
        case_id="auto-hgbl_dh",
        file="auto_hgbl_dh.json",
        label_ua="DIS-HGBL-DH — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для High-Grade B-Cell Lymphoma, Double-Hit / Triple-Hit. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_aggressive",
    ),
    CaseEntry(
        case_id="auto-hnscc",
        file="auto_hnscc.json",
        label_ua="DIS-HNSCC — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Head and neck squamous cell carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-hstcl",
        file="auto_hstcl.json",
        label_ua="DIS-HSTCL — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Hepatosplenic T-Cell Lymphoma. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-mastocytosis",
        file="auto_mastocytosis.json",
        label_ua="DIS-MASTOCYTOSIS — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Advanced systemic mastocytosis. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-mcl",
        file="auto_mcl.json",
        label_ua="DIS-MCL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Mantle Cell Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_aggressive",
    ),
    CaseEntry(
        case_id="auto-mds_hr",
        file="auto_mds_hr.json",
        label_ua="DIS-MDS-HR — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Myelodysplastic Syndromes — Higher Risk. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-mds_lr",
        file="auto_mds_lr.json",
        label_ua="DIS-MDS-LR — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Myelodysplastic Syndromes — Lower Risk. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-melanoma",
        file="auto_melanoma.json",
        label_ua="DIS-MELANOMA — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Cutaneous melanoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-mf_sezary",
        file="auto_mf_sezary.json",
        label_ua="DIS-MF-SEZARY — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Mycosis Fungoides / Sézary Syndrome. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-mm",
        file="auto_mm.json",
        label_ua="DIS-MM — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Multiple Myeloma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloma",
    ),
    CaseEntry(
        case_id="auto-mtc",
        file="auto_mtc.json",
        label_ua="DIS-MTC — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Medullary thyroid carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-nk_t_nasal",
        file="auto_nk_t_nasal.json",
        label_ua="DIS-NK-T-NASAL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Extranodal NK/T-Cell Lymphoma, Nasal Type. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-nlpbl",
        file="auto_nlpbl.json",
        label_ua="DIS-NLPBL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Nodular Lymphocyte-Predominant B-cell Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="hodgkin",
    ),
    CaseEntry(
        case_id="auto-nodal_mzl",
        file="auto_nodal_mzl.json",
        label_ua="DIS-NODAL-MZL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Nodal Marginal Zone Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_indolent",
    ),
    CaseEntry(
        case_id="auto-nsclc",
        file="auto_nsclc.json",
        label_ua="DIS-NSCLC — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Non-small cell lung cancer. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-ovarian",
        file="auto_ovarian.json",
        label_ua="DIS-OVARIAN — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Ovarian carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-pcnsl",
        file="auto_pcnsl.json",
        label_ua="DIS-PCNSL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Primary CNS Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_aggressive",
    ),
    CaseEntry(
        case_id="auto-pdac",
        file="auto_pdac.json",
        label_ua="DIS-PDAC — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Pancreatic ductal adenocarcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-pmbcl",
        file="auto_pmbcl.json",
        label_ua="DIS-PMBCL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Primary Mediastinal Large B-Cell Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_aggressive",
    ),
    CaseEntry(
        case_id="auto-pmf",
        file="auto_pmf.json",
        label_ua="DIS-PMF — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Primary Myelofibrosis. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-prostate",
        file="auto_prostate.json",
        label_ua="DIS-PROSTATE — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Prostate adenocarcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-ptcl_nos",
        file="auto_ptcl_nos.json",
        label_ua="DIS-PTCL-NOS — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Peripheral T-Cell Lymphoma, NOS. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-ptld",
        file="auto_ptld.json",
        label_ua="DIS-PTLD — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Post-Transplant Lymphoproliferative Disorder. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_aggressive",
    ),
    CaseEntry(
        case_id="auto-pv",
        file="auto_pv.json",
        label_ua="DIS-PV — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Polycythemia Vera. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="myeloid",
    ),
    CaseEntry(
        case_id="auto-rcc",
        file="auto_rcc.json",
        label_ua="DIS-RCC — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Renal cell carcinoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-sclc",
        file="auto_sclc.json",
        label_ua="DIS-SCLC — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Small cell lung cancer. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-splenic_mzl",
        file="auto_splenic_mzl.json",
        label_ua="DIS-SPLENIC-MZL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Splenic Marginal Zone Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_indolent",
    ),
    CaseEntry(
        case_id="auto-t_all",
        file="auto_t_all.json",
        label_ua="DIS-T-ALL — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для T-Lymphoblastic Leukemia/Lymphoma. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="lymphoblastic",
    ),
    CaseEntry(
        case_id="auto-t_pll",
        file="auto_t_pll.json",
        label_ua="DIS-T-PLL — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для T-Cell Prolymphocytic Leukemia. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="t_cell",
    ),
    CaseEntry(
        case_id="auto-urothelial",
        file="auto_urothelial.json",
        label_ua="DIS-UROTHELIAL — Auto-stub (75% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Urothelial carcinoma. Фактична наповненість бази для цієї хвороби — 75%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="solid",
    ),
    CaseEntry(
        case_id="auto-wm",
        file="auto_wm.json",
        label_ua="DIS-WM — Auto-stub (88% наповненість)",
        summary_ua="Автогенерований мінімальний профіль для Waldenström Macroglobulinemia / Lymphoplasmacytic Lymphoma. Фактична наповненість бази для цієї хвороби — 88%. Використовується для перевірки end-to-end engine + render — не для клінічних рішень.",
        badge="Auto-stub", badge_class="bdg-stub", category="b_indolent",
    ),
    # ── /AUTO-GENERATED ──

]
